.circleci/config.yml, Makefile
Ref #30 
- Persist workspace to reuse checkout code
- Use `ghr` for easier github releases
- Modify `Makefile` to download `kustomize` before launching `gen-yaml`
- Use `circleci workflow` to `build` for each commit or `build` then `publish-github-release` only on tag push
=> Automate admiral releases for new tags

Makefile
Kustomize made a release which was not related to the kustomize cli.
The trick is to retrieve all the release and get the last kustomize one.
=> Fix kustomize download

admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/controller/admiral/configmap.go, admiral/pkg/controller/admiral/configmap_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go, admiral/pkg/controller/common/types.go, admiral/pkg/controller/util/util.go, admiral/pkg/test/types.go, go.mod, go.sum
We noticed a bug where serviceentries are occasionally created with duplicate IPs. This is fixing that.
Still pending validation + writing tests.
=> Serviceentry to use a configmap for unique address cache

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/registry.go, admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/deployment_test.go, admiral/pkg/controller/admiral/pod.go, admiral/pkg/controller/common/types.go, go.mod, install/sample/base/greeting.yaml, install/sample/base/webapp.yaml
Also added a target group label to the setup that can eventually be used to route traffic between deployments based on an arbitrary label 
=> Making labels configurable

admiral/pkg/controller/admiral/dependency_test.go, admiral/pkg/controller/admiral/globaltraffic_test.go, admiral/pkg/controller/admiral/node_test.go, admiral/pkg/controller/admiral/pod.go, admiral/pkg/controller/admiral/pod_test.go, admiral/pkg/test/mock.go
Tests for the create___Controller methods for controllers in the pkg/controller/admiral directory 
=> Tests for creating controllers

admiral/pkg/clusters/serviceentry.go
This should fix a segmentation fault I encountered where services were not matched by `getServiceForDeployment` but the nil value was still added to `sourceServices`
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13f6328]
goroutine 171 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190208202428-1a579f8a7b42/pkg/util/runtime/runtime.go:58 +0x108
panic(0x155ba60, 0x259cce0)
/usr/local/go/src/runtime/panic.go:513 +0x1b9 …
```
=> Skip service instances that were not matched

Makefile
Some of these would likely need to be overridden if one wanted to have an in-house build or do local development in a cluster.
In my development env I use KinD to spin up several clusters as a sandbox. This makes that a lot easier for me because I can 
1. set `imagePullPolicy: always` on the admiral deployment and set the image to a repo I control
2. build an image with dlv, to which I can attach a debugger and push it to a remote repo
After build and push, I force the deployment to roll a new replica by changing an annotation:
```bash
#!/bin/bash
set -ex
DOCKER_REPO=myrepo \
DOCKER_USER=myuser \
DOCKER_PASS=mypass \
make \
build-linux \
docker-build \
docker-publish
kubectl patch -n admiral deployment admiral -p '{"spec": {"template": {"metadata": {"annotations": {"v": "'$(cat …
```
=> Allow overriding some values to for development and debugging

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/service.go, admiral/pkg/controller/admiral/service_test.go
This allows use in environments which do not provide LoadBalancers by using the first externalIP from `service.spec.externalIPs`.
=> Allow use of externalIPs for envs without LBs

admiral/docker/Dockerfile.admiral
This moves us from ubuntu 16.04 -> 20.04, as well as doing the aptitude work a single RUN step with cache removal afterwards
=> Dockerfile modernization

Makefile
=> Fixing broken method for downloading kustomize

.circleci/config.yml, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/types.go
Signed-off-by: Mengying <mengyinglimandy@gmail.com>
=> added the cluster id inside deployment controller

.circleci/config.yml, .github/workflows/golang-ci-lint.yml, admiral/pkg/apis/admiral/routes/handlers.go, admiral/pkg/apis/admiral/server/server.go, tests/create_cluster.sh
CI builds are failing due to the certificate change shown [here](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). Updating to the latest image from Circle CI fixes this problem and allows Admiral to build again as expected. 
Fixed linter to run though  did not make changes to any current files to limit this to just fixing CI and not lint issues.
=> Fix CircleCI build and Golang linting

admiral/pkg/clusters/types.go, admiral/pkg/clusters/types_test.go
Fixes #168 
Added check before using RolloutClient to avoid nil deference when *ArgoRolloutsEnabled=false*, as it will not get initialized when set to false.
=> fix: Admiral crash when ArgoRolloutsEnabled set to false

admiral/pkg/clusters/serviceentry.go
Fix meshPort nil for canary rollout without weighted services
=> Fix meshPort nil 

admiral/pkg/clusters/serviceentry.go
`weightedServices` was initialized with K8s services without the source cluster context, which results in wrong weightedServices being used when the service existed in multiple cluster. 
The PR fixes the issue by initializing `sourceWeightedServices` with source cluster as key and use it for endpoint's local FQDN.
=> fix: weighted services for source

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
Argo rollouts can be defined without any rollout strategy. When this happens admiral panics because the code was fetch the Strategy when Strategy was empty.
=> [bug] prevent panic when finding out rollout strategy

admiral/pkg/controller/common/types.go, admiral/pkg/controller/common/types_test.go
Fixes #219
Added mutex to sync access to the SidecarEgressMap
=> Added mutex to sync access to the SidecarEgressMap

admiral/pkg/clusters/types.go, admiral/pkg/clusters/types_test.go
Fixes #221  process gtps as soon they are applied
Signed-off-by: Shriram Sharma <shriram_sharma@intuit.com>
=> process gtps as soon they are applied

admiral/pkg/controller/admiral/configmap_test.go, admiral/pkg/controller/admiral/globaltraffic_test.go, admiral/pkg/controller/admiral/rollouts.go
This should fix the failing test
https://app.circleci.com/pipelines/github/istio-ecosystem/admiral/785/workflows/c3027498-b229-4781-ae37-eba8ef298b4b/jobs/1186
=> fixing the broken gtp tests

docs/Examples.md
This PR fixes a think-o in the installations steps:
- Step1: set the `REMOTE_CLUSTER` env variable as `REMOTE_CLUSTER=<path_to_kubeconfig_for_remote_cluster>`.  
- Step 4: use `REMOTE_CLUSTER` as a context.
=> Fix Admiral install in the Examples document

admiral/pkg/controller/admiral/globaltraffic_test.go
The GTP cache test was failing intermittently since the test was dependent on the order in which the map returned the GTPs.
Signed-off-by: Shriram Sharma <shriram_sharma@intuit.com>
=> fixed the failing GTP test

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go
When canary.trafficRouting is not defined for Argo rollout canary strategy.
**Expected:**
The service match should return whichever service has a mesh port defined for creating service entry.
**Found:**
Admiral by default tries to match with the stable K8s service defined within rollout.stableService and if mesh port is not found in that K8s service, the Service Entry creation fails.
**Fix:**
When `canary.trafficRouting` is not defined for Argo rollout canary strategy. Scenario 1 from below should be expected.
**Overall Expected:**
Scenario 1 - canary strategy defined and stable service is non empty
Pick stable service if present otherwise first service that matches
Scenario 2 -  canary strategy defined with istio traffic management
Pick stable service/canary services defined in canary …
=> fix: Rollout canary when traffic routing not defined

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
When a replicated VS is deleted in the source cluster, it gets deleted in clusters where it is replicated in. During this process, if the deletion fails due to some reason, it skips deleting the vs from the remaining clusters. 
This PR changes that behavior, and makes it consistent with deletion workflow for DestinationRules, and ServiceEntries, where it logs that there was an error and continues deleting the resource in other clusters.
=> log error, instead of returning when vs deletion fails

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go
This change adds a default HTTP connection pool configuration to the DestinationRule
=> Add default connection pool parameters for generated cnames

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
Updates to avoid creation of service entry with dummy endpoints. Include updates to delete existing service entry with only dummy endpoints.
=> Stop creation of service entires with dummy endpoints

admiral/pkg/clusters/envoyfilter.go, admiral/pkg/clusters/envoyfilter_test.go, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/types.go, admiral/pkg/clusters/types_test.go
3 Changes - 
- Removing duplicate controllers
- Adding read-only mode to ensure only primary admiral can update entries
- Adding plugin info into envoyFilter
=> Updating with fixes

admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/deployment_test.go
Given deployment cache has a valid deployment in its cache
And the deployment does not have an env annotation
And a debug deployment exists, without the env annotation
And debug deployment has the admiral.io/ignore annotation set to true,
And the env key is derived from namespace
When admiral receives an update event for the debug deployment, admiral calls [this](https://github.com/istio-ecosystem/admiral/blob/13daaf07a6e553a4e6d8a01491e68d68183762c8/admiral/pkg/controller/admiral/deployment.go#L140) function
Then, the valid deployment is deleted because the deployment cache stores the deployment by key, which is the same for the valid deployment, as well as the debug deployment.
To prevent admiral from deleting the valid deployment, it will now match the deployment name it found in its …
=> check deployment name before deleting deployment from cache

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
=> skipped updating istio resources which were not created by admiral

.gitignore, CONTRIBUTING.md, Makefile, install/sample/overlays/rollout-bluegreen/kustomization.yaml, install/sample/overlays/rollout-bluegreen/namespace.yaml, install/sample/overlays/rollout-canary/kustomization.yaml, install/sample/overlays/rollout-canary/namespace.yaml, tests/create_cluster.sh, tests/install_istio.sh, tests/run.sh
Updating instructions for apple silicon, updating kustomize as 3.8.2 version is not supported in apple silicon.
=> Updating kustomize version and adding apple silicon instructions

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
Update to SE modification flow, in order to add env, prefix and associated GTP details to SE labels.
=> Adding labels to admiral generated service entries

Makefile, admiral/pkg/clusters/dependencyproxy.go, admiral/pkg/clusters/dependencyproxyConverter.go, admiral/pkg/clusters/dependencyproxyConverter_test.go, admiral/pkg/clusters/dependencyproxy_test.go, admiral/pkg/clusters/envoyfilter_test.go, admiral/pkg/clusters/handler.go, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/types.go, install/admiral/base/role_bindings.yaml, install/admiral/base/roles.yaml, install/sample/base/kustomization.yaml, install/sample/depProxyExample.yaml, install/sample/proxy.yaml, install/sample/sample_dep.yaml, install/scripts/install_sample_services.sh, tests/run.sh, tests/test7.sh
=> Generate VirtualServices based on DependencyProxy

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go
The additional endpoints will be generated based on the `additional_endpoints_suffixes` array passed as the command line param. 
Admiral will use the passed suffixes to generate the endpoints by creating a VirtualService, which will route the corresponding ServiceEntry endpoint
=> provided an ability to create additional endpoints

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go
ConsecutiveGatewayErrors in DestinationRule do not take affect the value is higher that consecutive5xxErrors.
In [envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-consecutive-5xx) consecutive5xxErrors value is set to 5 by default. 
consecutive5xxErrors needs to be set to 0, to explicitly disable the 5XX error outlier detection to kick in.
=> [MESH-3036] - Set consecutive5xxErrors to 0

admiral/pkg/clusters/types.go
Add a log line similar to the one in [HandleEventForRollout](https://github.com/istio-ecosystem/admiral/blob/master/admiral/pkg/clusters/types.go#L629)
=> Add received log line for HandleEventForDeployment

admiral/pkg/registry/registry.go
Adds an interface for fetching configurations for a given identity, or all the identities in a given cluister.
=> add interface for getting configurations

admiral/pkg/controller/admiral/controller.go, go.mod, go.sum
added status check along with generation check
Thank you!
=> added status check along with generation check

admiral/pkg/clusters/configwriter.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/shard_handler.go, admiral/pkg/registry/registry.go
=> add time metrics

admiral/pkg/clusters/outlierdetection_handler_test.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/serviceentry_od_test.go, admiral/pkg/controller/secret/secretcontroller.go
This fixed the default secret resolver intialization. It was broken during the merge.
Thank you!
=> fixed the secret resolver intialization

admiral/pkg/clusters/shard_handler.go, admiral/pkg/clusters/shard_handler_test.go, admiral/pkg/controller/admiral/shard.go, admiral/pkg/test/mock.go
Shard handler now updates the shard status while producing networking resources from it.
Added tests for some of the shard status processing methods.
=> Update Shard status processing

admiral/pkg/clusters/configwriter.go, admiral/pkg/clusters/configwriter_test.go, admiral/pkg/registry/config.go
Handle weighted rollouts
Handle unweighted deployments and rollouts by sorting services and taking the first one
=> Handle weighted services

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_handler.go, admiral/pkg/clusters/virtualservice_handler_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go
This change would generate VS exported to ingress running in passthrough mode.
Thank you!
=> generating ingress virtualservice to enable cross-cluster communication with passthrough gateway

.circleci/config.yml, admiral/pkg/clusters/virtualservice_handler.go, admiral/pkg/clusters/virtualservice_handler_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go
This change makes sure that the virtual service that gets copied across different clusters does not get over-written. It assumes that the namespace-vsname combination is unique.
Thank you!
=> Mesh 3865 - Adding unique VS name for copy VS feature

admiral/pkg/controller/admiral/controller.go, admiral/pkg/controller/admiral/controller_test.go
Previously, we were attempting to cast []*v1.Service to metav1.Object. This is because the cached services are stored as slices, as each identity could have more than one service. Instead, we check the service that we got the event for against each of the services in the slice to pick the right one in the cache to cast to metav1.Object.
Thank you!
=> fix casting of slices of services

admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/admiral/node.go, admiral/pkg/controller/admiral/node_test.go
- Added `Locality` field to `WorkloadEntry` in `serviceentry_test.go`.
- Implemented `validateLocalityInServiceEntry` function to check locality in service entries.
- Integrated locality validation in service entry reconciliation logic.
- Modified `NewNodeController` to accept `resyncPeriod` parameter.
- Updated tests to reflect changes in `NewNodeController` signature.
Thank you!
=> [MESH-5509] Ensure Locality Label in Service Entries

admiral/pkg/clusters/envoyfilter.go, admiral/pkg/clusters/envoyfilter_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go
- Added `IsAGateway` and `GetPartitionAndOriginalIdentifierFromPartitionedIdentifier` functions in `common.go` to validate and parse gateway asset aliases.
- Introduced `GetWorkloadSelectorLabels` function in `envoyfilter.go` to generate workload selector labels based on asset aliases.
- Updated `constructEnvoyFilterStruct` to use `GetWorkloadSelectorLabels`.
- Added unit tests for the new functions in `common_test.go` and `envoyfilter_test.go`.
- Included `GatewayAssetAliases` in test configurations.
Thank you!
=> [MESH-5465] Add validation and utility functions for identities with partitions

admiral/pkg/clusters/configwriter.go, admiral/pkg/clusters/configwriter_test.go, admiral/pkg/clusters/destinationrule_handler_test.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_handler_test.go, admiral/pkg/clusters/serviceentry_od_test.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/shard_handler_test.go, admiral/pkg/clusters/util_test.go, admiral/pkg/controller/util/migration.go, admiral/pkg/controller/util/migration_test.go
- Updated various test cases to include the 'security.istio.io/tlsMode' label in Service Entries and Workload Entries.
- Modified validation logic to check for the presence of the 'security.istio.io/tlsMode' label.
- Refactored code to ensure the 'security.istio.io/tlsMode' label is added where necessary.
- Enhanced error handling in validation functions to provide detailed error messages.
Thank you!
=> [MESH-5515] Add 'security.istio.io/tlsMode' label to SE endpoints for deployment to rollout migration usecase

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go, admiral/pkg/util/constants.go
Generates the DR which applied to the ingress in order to facilitate VS based cross cluster routing
=> generating ingress DR for VS based routing

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go
Added a cluster allow list to specify on which source clusters VS based routing should be enabled.
=> added a cluster allowlist param for vs based routing

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go, install/admiralremote/base/remote.yaml
Looks like there is a bug while trying to create VS with SNI host in any other NS apart from `istio-system` NS.
To circumvent that, I changed to create the routing VS in the istio-system NS for now. Will create an issue with istio community.
=> creating routing vs in the istio-system ns instead

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go
=> Fix command stringarr toslice

admiral/pkg/controller/admiral/job.go, admiral/pkg/controller/admiral/monovertex.go, admiral/pkg/controller/admiral/vertex.go
=> Always process an Add operation for client discovery

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go
* MESH-000: Implement split-brain prevention logic
- Added `PreventSplitBrain` flag to enable/disable explicit split-brain prevention logic.
- Introduced `orderSourceClusters` function to prioritize clusters based on GTP preference region.
- Updated `updateGlobalGtpCache` to utilize context for GTP preference region handling.
- Added utility functions `GetGtpPreferenceRegion` and `makeDnsPrefixRegionMapping` for GTP region mapping.
- Updated tests to include split-brain prevention scenarios.
Thank you!
=> MESH-000-Solve Split Brain (#823)

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/dependency_handler.go, admiral/pkg/clusters/deployment_handler.go, admiral/pkg/clusters/rollout_handler.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/types.go, admiral/pkg/clusters/util.go, admiral/pkg/clusters/util_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go
* MESH-000: Implement client-initiated processing feature
- Added `ClientInitiatedProcessingEnabled` flag to enable/disable client-initiated processing.
- Introduced `processClientDependencyRecord` function to handle client dependencies.
- Refactored code to utilize `processDestinationsForSourceIdentity` for processing destinations.
- Added `ClientClusterNamespaceServerCache` to `RemoteRegistry` for caching client cluster namespaces.
- Updated deployment and rollout handlers to incorporate client-initiated processing logic.
- Created new data structures `MapOfMapOfMapsOfMaps` for enhanced caching capabilities.
Thank you!
=> MESH-000: Implement client-initiated processing feature (#815)

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/routingpolicy_handler.go, admiral/pkg/clusters/routingpolicy_handler_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go
- Add param routing_policy_enabled_clusters to enable processing
- Update routing_handler to use routing_policy_enabled_clusters before add,update or delete
MESH-5938
Thank you!
=> MESH-5938: Admiral should not create EF for RoutingPolicy on cluster that are not DRS enabled.

admiral/pkg/clusters/serviceentry.go
These are metrics used to test new monitoring capabilities for Admiral 2.0. They should be removed from the current Admiral as they are overloading the sample limit.
=> MESH-0000: remove metrics due to sample limit

Makefile, admiral/pkg/clusters/clientdiscovery_handler_test.go, admiral/pkg/clusters/handler_test.go, admiral/pkg/controller/admiral/shard_test.go, admiral/pkg/test/mock.go
Description:
- Increase overall coverage.
Thank you!
=> MESH-5688: Tech-Debt: Increase coverage

admiral/pkg/controller/admiral/shard_test.go
- Drop test that causes a race condition failure by go
Thank you!
=> Regression: Drop flaky test

admiral/pkg/clusters/dependency_handler.go, admiral/pkg/clusters/dependency_handler_test.go, admiral/pkg/clusters/envoyfilter_test.go, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/routingpolicy_handler.go, admiral/pkg/clusters/routingpolicy_handler_test.go, admiral/pkg/clusters/types.go, admiral/pkg/controller/admiral/routingpolicy.go, admiral/pkg/controller/admiral/routingpolicy_test.go, admiral/pkg/test/mock.go
Task
- Admiral should process new client onboardings for a service with a RoutingPolicy
- Introduce RoutingPolicyProcessor interface to contain the process() api in order to expose it
Thank you!
=> MESH-5878: Admiral does not create envoy filter on client onboardings

admiral/apis/v1/types.go, admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/admiralDatabaseClient.go, admiral/pkg/clusters/admiralDatabaseClient_test.go, admiral/pkg/clusters/dynamoDB.go, admiral/pkg/clusters/dynamoDB_test.go, admiral/pkg/clusters/testdata/admiralDatabaseClientConfig_invalid.yaml, admiral/pkg/clusters/testdata/admiralDatabaseClientConfig_is_valid.yaml, admiral/pkg/clusters/types.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go
Adding support for pushing dynamic config.
Thank you!
=> Enable Dynamic Config Push

admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
Handle incluster and routing vs based routing configuration for canary rollouts, when the weighted services are one for the route destinations
Thank you!
=> handle canary rollout weight for destination with one weighted service

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
made cartographer VS check conditional
The cartographer VS check is only needed to verify if .mesh DR should be pinned. This check is not needed anywhere else.
=> made cartographer VS check conditional
