istio-ecosystem/admiral

admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go
Added "disable-update" label to skip any updates to istio resource
=> Adding label to skip admiral generated istio resource update

admiral/pkg/controller/admiral/service_test.go
=> Tests for service controller

install/admiral/base/deployments.yaml, install/admiral/base/role_bindings.yaml, install/admiral/base/roles.yaml, install/admiral/base/service_accounts.yaml, install/admiral/overlays/demosinglecluster/envconfig_values.yaml, install/admiral/overlays/demosinglecluster/kustomization.yaml
=> Fixing demo to use admiral-sync for sync namespace

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/handler.go, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/types.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go, admiral/pkg/controller/istio/sidecar.go, admiral/pkg/controller/istio/sidecar_test.go, admiral/pkg/test/mock.go, go.sum
Code changes to update the sidecar resource with the workload namespace
=> Update sidecar resource in workload namespace

admiral/pkg/controller/admiral/controller.go, admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/deployment_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/types.go, docs/Examples.md, install/admiralremote/base/remote.yaml, install/sample/base/webapp.yaml
finished first draft for recognizing admiral ignore annotation, ready for review, fixed some typos and 404 link for helm install
=> Add ignore annotation to skip deployments/namespaces

admiral/pkg/clusters/handler.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/deployment_test.go, admiral/pkg/controller/admiral/rollouts.go, admiral/pkg/controller/admiral/rollouts_test.go
Not ready to merge still working on the changes
=> Clean up cache entry when deployment needs to be ignored.

docs/Examples.md
Remove invalid flag from `kubectl logs` command
=> Fix logs command

.circleci/config.yml, admiral/pkg/apis/admiral/routes/handler_test.go, admiral/pkg/apis/admiral/routes/handlers.go, admiral/pkg/apis/admiral/routes/routes.go, admiral/pkg/apis/admiral/server/server.go, admiral/pkg/clusters/handler.go, admiral/pkg/clusters/handler_test.go, admiral/pkg/clusters/registry.go, admiral/pkg/clusters/registry_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/types.go, admiral/pkg/clusters/types_test.go, admiral/pkg/controller/admiral/service.go, admiral/pkg/controller/admiral/service_test.go, admiral/pkg/controller/secret/secretcontroller.go, admiral/pkg/controller/secret/secretcontroller_test.go
Admiral APIs - 
1. Get all clusters admiral is watching
2. Get all se by cluster name
3. Get all se by service identity
=> Admiral apis

CONTRIBUTING.md, Makefile, install/admiral/base/deployments.yaml, install/admiral/base/kustomization.yaml, install/admiral/base/services.yaml, install/prometheus/prometheus.yaml, install/scripts/install_admiral.sh, install/scripts/install_prometheus.sh
- Add kustomize template to install prometheus for scraping metrics
- Update admiral kustomize template for scraping by prometheus
- Add install script for prometheus
- Update CONTRIBUTING doc
Signed-off-by: Adil Fulara <adil.fulara@gmail.com>
=> Prometheus Install in demo cluster

Makefile
=> fixed the crd-gen

Makefile
=> fixed model-gen

install/admiralremote/base/remote.yaml, install/scripts/cluster-secret.sh
=> Fixes #306 manually generating sa token

README.md
=> Add links to Readme

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/configSyncer.go, admiral/pkg/clusters/configwriter.go, admiral/pkg/clusters/configwriter_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/shard_handler.go, admiral/pkg/clusters/shard_handler_test.go, admiral/pkg/clusters/testdata/ppdmeshtestblackholeIdentityConfiguration.json, admiral/pkg/clusters/testdata/ppdmeshtestinboundsIdentityConfiguration.json, admiral/pkg/clusters/testdata/sampleIdentityConfiguration.json, admiral/pkg/clusters/types.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go, admiral/pkg/registry/configCache.go, admiral/pkg/registry/configSyncer.go, admiral/pkg/registry/configWriter.go, admiral/pkg/registry/registry.go, admiral/pkg/registry/registry_test.go, admiral/pkg/registry/testdata/sampleIdentityConfiguration.json, admiral/pkg/registry/testutils.go
Signed-off-by: Ryan Tay <ryan_tay@intuit.com>
Co-authored-by: Anubhav Aeron <anubhav_aeron@intuit.com>
Co-authored-by: nirvanagit <anubhavaeron@gmail.com>
=> Implement Operator functionality

admiral/pkg/clusters/serviceentry.go
=> [MESH-5336] - Adding error cluster to logs to debug better

admiral/apis/v1/types.go, admiral/pkg/clusters/serviceentry.go
=> Remove unused constant

admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
Added default warmupDurationSeconds to the ingress DR
=> added warmupDurationSeconds to ingress DR

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
Added GTP DNS Prefixed FQDN to the VS RouteDestinations
=> added the gtp implementation

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go
Added additional logs for VS based routing
=> added additional logs for debugging purposes

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go
removed the dot from the local domain in VS
=> removed the dot from the local domain in VS

admiral/pkg/clusters/destinationrule_handler.go, admiral/pkg/clusters/destinationrule_handler_test.go
fixes issue https://github.com/istio-ecosystem/admiral/issues/352 
Thank you!
=> fixing incorrect update logic for retry on conflict for updating destination rule

install/sample/greetings-ccc.yaml
=> added a sample client connection config

admiral/cmd/admiral/cmd/root.go, admiral/pkg/controller/admiral/job.go, admiral/pkg/controller/admiral/monovertex.go, admiral/pkg/controller/admiral/vertex.go
=> Safe check Metadata existence, change to slicevar

admiral/pkg/clusters/serviceentry.go
This fixes the incorrect DR being vended in sourceClusters.
=> fixed the incorrect dr issue

admiral/cmd/admiral/cmd/root.go, admiral/pkg/controller/admiral/clientconnectionconfigcontroller.go, admiral/pkg/controller/admiral/controller.go, admiral/pkg/controller/admiral/delegator_mock_test.go, admiral/pkg/controller/admiral/dependency.go, admiral/pkg/controller/admiral/deployment.go, admiral/pkg/controller/admiral/deployment_test.go, admiral/pkg/controller/admiral/envoyfilter.go, admiral/pkg/controller/admiral/globaltraffic.go, admiral/pkg/controller/admiral/job.go, admiral/pkg/controller/admiral/monovertex.go, admiral/pkg/controller/admiral/node.go, admiral/pkg/controller/admiral/outlierdetection.go, admiral/pkg/controller/admiral/rollouts.go, admiral/pkg/controller/admiral/rollouts_test.go, admiral/pkg/controller/admiral/routingpolicy.go, admiral/pkg/controller/admiral/service.go, admiral/pkg/controller/admiral/shard.go, admiral/pkg/controller/admiral/vertex.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/types.go, admiral/pkg/controller/istio/destinationrule.go, admiral/pkg/controller/istio/serviceentry.go, admiral/pkg/controller/istio/sidecar.go, admiral/pkg/controller/istio/virtualservice.go
This is to skip events if only replica count is changed.
Thank you!
=> Add replica count check

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
fix duplicate vs issue in vs based routing
=> fix duplicate vs issue in vs based routing

admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/common_test.go
=>  If present sort GTPs based on update time

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go
enable warm duration through runtime param
=> enable warm duration through runtime param

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/shard_handler_test.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go, admiral/pkg/controller/common/types.go
replaced allow list with exclusion list for vs based routing
=> replaced allow list with exclusion list for vs based routing

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go
fixed the vs routing exclusion cluster bug
=> fixed the vs routing exclusion cluster bug

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go
=> fixed panic in modifySE

admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
added weights for multiple destinations per match
=> added weights for multiple destinations per match

admiral/pkg/clusters/virtualservice_routing.go
moved exportTo to generateInClusterVS func
=> moved exportTo to generateInClusterVS func

admiral/pkg/clusters/destinationrule_handler.go, admiral/pkg/clusters/destinationrule_handler_test.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/controller/common/common.go, admiral/pkg/controller/common/config.go, admiral/pkg/controller/common/config_test.go
Updates the admiral-sync namespace destination rule when in cluster vs based routing is enabled for a source cluster and identity
Thank you!
=> Update destination rule for in-cluster vs based routing

admiral/pkg/clusters/serviceentry.go
Re-factored code for GTP processing for in-cluster VS. GTP will be processed only when destinations are determined for the given rollout/deployment
[MESH-6477](https://jira.intuit.com/browse/MESH-6477)
Thank you!
=> MESH-6477: re-factor in-cluster vs GTP processing

admiral/cmd/admiral/cmd/root.go, admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/virtualservice_routing.go, admiral/pkg/clusters/virtualservice_routing_test.go
added reconciliation check for routing dr
=> added reconciliation check for routing dr

admiral/pkg/clusters/virtualservice_routing.go
fixed the GTP failover vs merge
=> fixed the GTP failover vs merge

admiral/pkg/clusters/virtualservice_handler.go
=> fixed the case senstivity

admiral/pkg/clusters/serviceentry.go
=> fixed the DR pinning

admiral/pkg/clusters/virtualservice_handler.go, admiral/pkg/clusters/virtualservice_handler_test.go
=> fixed custom VS case

admiral/pkg/clusters/serviceentry.go, admiral/pkg/clusters/serviceentry_test.go, admiral/pkg/clusters/shard_handler.go, admiral/pkg/controller/istio/virtualservice.go, admiral/pkg/controller/istio/virtualservice_test.go
fixed dr pinning for custom vs in identity ns
=> fixed dr pinning for custom vs in identity ns
